services:
  mongodb:
    image: mongo:latest
    container_name: ecommerce_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}

  web:
    build: .
    container_name: ecommerce_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - DEBUG=True
      - DB_HOST=mongodb
      - DB_PORT=27017
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    restart: always

volumes:
  mongo_data:
